server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ITSM
          uri: http://localhost:8082
          predicates:
            - Path=/troubleTickets/**, 
        - id: BPM
          uri: http://localhost:8083
          predicates:
            - Path=/processInstances/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ITSM
          uri: http://itsm:8080
          predicates:
            - Path=/troubleTickets/**, 
        - id: BPM
          uri: http://bpm:8080
          predicates:
            - Path=/processInstances/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
